function uncertainty=serpentSensitivityDataProcess(fileName)
%Script file: serpentSensitivityDataProcess.m
%
%Purpose:
%This script is used to process sensitivity data file
%generated by SERPENT. This function returns the uncertainty value.
%
%Argument:
%fileName is the name of sensitivity data file generated by SERPENT2
%without _sens.m. For example, if the data file is "core_2d_boc_sens.m", fileName
%should be "core_2d_boc".
%
%Author: Jin Li
%Date: November 17, 2017

if exist('temp.mat','file')
    delete temp.mat;
end
save('temp.mat','fileName');

run('initialize.m');
run('arrangeSensitivity.m');
run('sortSensitivity.m');
run('plotSensitivityStairs.m');
run('calculateUncertainty.m');
run('arrangeUncertainty.m');
run('sortUncertainty.m');
run('plotUncertaintyStairs.m');
uncertainty=sqrt(cell2mat(struct2cell(load('temp.mat','totalUncertainty'))));
delete temp.mat
